services:
  mysql:
    #image: mysql:latest #for mac intel, windows
    image: arm64v8/mysql:9.0.1
    container_name: mysql_container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "" # Blank password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "shopapp_online"
    restart: always
